DROP TABLE IF EXISTS KONTAKT_ZAHTJEV;
DROP TABLE IF EXISTS NEKRETNINA;
DROP TABLE IF EXISTS AGENT;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS LOKACIJA;
DROP TABLE IF EXISTS TIP_NEKRETNINE;
DROP TABLE IF EXISTS KORISNIK;

CREATE TABLE KORISNIK
(
  korisnik_id SERIAL PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  lozinka VARCHAR(255) NOT NULL,
  ime VARCHAR(50) NOT NULL,
  prezime VARCHAR(50) NOT NULL
);

CREATE TABLE TIP_NEKRETNINE
(
  tip_nekretnine_id SERIAL PRIMARY KEY,
  naziv VARCHAR(50) NOT NULL,
  opis VARCHAR NOT NULL
);

CREATE TABLE LOKACIJA
(
  lokacija_id SERIAL PRIMARY KEY,
  adresa VARCHAR(100) NOT NULL,
  grad VARCHAR(50) NOT NULL,
  drzava VARCHAR(50) NOT NULL
);

CREATE TABLE AGENT
(
  agent_id INT PRIMARY KEY,
  datum_zaposlenja DATE NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES KORISNIK(korisnik_id)
);

CREATE TABLE ADMIN
(
  admin_id INT PRIMARY KEY,
  dozvole VARCHAR(50) NOT NULL,
  FOREIGN KEY (admin_id) REFERENCES KORISNIK(korisnik_id)
);

CREATE TABLE NEKRETNINA
(
  nekretnina_id SERIAL PRIMARY KEY,
  naslov VARCHAR(100) NOT NULL,
  opis VARCHAR NOT NULL,
  cijena FLOAT NOT NULL,
  povrsina FLOAT NOT NULL,
  status VARCHAR(20) NOT NULL,
  lokacija_id INT NOT NULL,
  tip_nekretnine_id INT NOT NULL,
  agent_id INT NOT NULL,
  FOREIGN KEY (lokacija_id) REFERENCES LOKACIJA(lokacija_id),
  FOREIGN KEY (tip_nekretnine_id) REFERENCES TIP_NEKRETNINE(tip_nekretnine_id),
  FOREIGN KEY (agent_id) REFERENCES AGENT(agent_id)
);

CREATE TABLE KONTAKT_ZAHTJEV
(
  zahtjev_id SERIAL PRIMARY KEY,
  poruka VARCHAR NOT NULL,
  nekretnina_id INT NOT NULL,
  korisnik_id INT NOT NULL,
  agent_id INT NOT NULL,
  FOREIGN KEY (nekretnina_id) REFERENCES NEKRETNINA(nekretnina_id),
  FOREIGN KEY (korisnik_id) REFERENCES KORISNIK(korisnik_id),
  FOREIGN KEY (agent_id) REFERENCES AGENT(agent_id)
);